#!/bin/bash
# herbstluftwm - autostart

hc() { herbstclient "$@"; }

# vars
mod=Mod4
resizestep=0.05
term=st
docterm="st -f PragmataPro:size=14"
launcher1="rofi -show run"
launcher2="rofi -show ssh"
locker=slock

hc emit_hook reload
# shellcheck disable=SC1090
[[ -f ~/.fehbg ]] && source ~/.fehbg

# keybindings
hc keyunbind --all

# tags
tagnames=(m s w t1 t2 b)
hc rename default "${tagnames[0]}" 2>/dev/null || true
for i in "${!tagnames[@]}"; do
    key=$((i+1))
    hc add "${tagnames[$i]}"
    if ((key<10)); then
        hc keybind "$mod-$key" use_index "$i"
        hc keybind "$mod-Shift-$key" move_index "$i"
    fi
done

hc detect_monitors

# core
hc keybind $mod-Shift-q quit
hc keybind $mod-Shift-r reload

# focus
hc keybind $mod-h focus left
hc keybind $mod-j focus down
hc keybind $mod-k focus up
hc keybind $mod-l focus right
hc keybind $mod-i jumpto urgent

# moving
hc keybind $mod-Shift-h shift left
hc keybind $mod-Shift-j shift down
hc keybind $mod-Shift-k shift up
hc keybind $mod-Shift-l shift right

# resizing
hc keybind $mod-Control-h resize left +$resizestep
hc keybind $mod-Control-j resize down +$resizestep
hc keybind $mod-Control-k resize up +$resizestep
hc keybind $mod-Control-l resize right +$resizestep

# splitting

# layouts
hc keybind $mod-F5  spawn ~/bin/herb/layouter irc
hc keybind $mod-F6  spawn ~/bin/herb/layouter sys
hc keybind $mod-F7  spawn ~/bin/herb/layouter basic
hc keybind $mod-F8  spawn ~/bin/herb/layouter lefty
hc keybind $mod-F9  spawn ~/bin/herb/layouter righty

# layouting
hc keybind $mod-x             remove
hc keybind $mod-Shift-x       close_and_remove
hc keybind $mod-s             floating toggle
hc keybind $mod-f             fullscreen toggle
hc keybind $mod-p             pseudotile toggle
hc keybind $mod-Shift-Tab     cycle_layout 1
hc keybind $mod-Tab           cycle
hc keybind $mod-Home          rotate
hc keybind $mod-Control-space split explode

# spawns
hc keybind $mod-Return spawn $term
hc keybind $mod-Shift-Return spawn $docterm
hc keybind $mod-Shift-Delete spawn ~/bin/herb/closeall
hc keybind $mod-space spawn $launcher1
hc keybind $mod-Shift-space spawn $launcher2
hc keybind $mod-F11 spawn $locker

# chains
hc keybind $mod-Left  chain , split left 0.5 , focus left , spawn "$term"
hc keybind $mod-Down  chain , split bottom 0.5 , focus down , spawn "$term"
hc keybind $mod-Up    chain , split top 0.5 , focus up , spawn "$term"
hc keybind $mod-Right chain , split right 0.5 , focus right , spawn "$term"

# cycling
hc keybind $mod-period use_index +1 --skip-visible
hc keybind $mod-comma  use_index -1 --skip-visible
hc keybind $mod-equal cycle_monitor +1
hc keybind $mod-minus cycle_monitor -1

# mouse
hc mouseunbind --all
hc mousebind $mod-Button1 move
hc mousebind $mod-Button3 resize
hc mousebind $mod-Shift-Button3 zoom


# settings
hc set default_frame_layout 2
hc set snap_gap 10
hc set snap_distance 10
hc set focus_stealing_prevention 1
hc set swap_monitors_to_get_tag 1
hc set tree_style '╾│ ├╰╼─╮'


# theme
hc attr theme.reset 1
hc set frame_gap 10
hc set frame_bg_transparent 1
hc set frame_border_width 0
hc set window_gap 1
hc set window_border_width 3
hc set window_border_active_color '#ed3'
hc set window_border_normal_color '#777'
hc set window_border_urgent_color '#e55'


# rules
hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# gimp
# TODO move this to a gimp-launch script that cleans up this shit
#hc add gimp
#hc load gimp '
#(split horizontal:0.850000:0
#(split horizontal:0.200000:1
#(clients vertical:0)
#(clients grid:0))
#(clients vertical:0))
#'
#hc rule class=Gimp tag=gimp index=01 pseudotile=on
#hc rule class=Gimp windowrole~'gimp-(image-window|toolbox|dock)' pseudotile=off
#hc rule class=Gimp windowrole=gimp-toolbox focus=off index=00
#hc rule class=Gimp windowrole=gimp-dock focus=off index=1


# finish up
hc unlock


# panel(s) and monitor focus keybinds
panel=~/bin/herb/np.sh
for m in $(herbstclient list_monitors | cut -d: -f1); do
    "$panel" "$m" &
	hc keybind "$mod-Alt-F$m" focus_monitor "$m"
done


# local extras
lcfg=~/.config/herbstluftwm/$(hostname)
[[ -f $lcfg ]] && $lcfg $mod
