#!/bin/bash

# herbstluftwm - autostart
#
# mel@thestack.co

hc() { herbstclient "$@"; }

# vars
mod=Mod4
resizestep=0.05
term=urxvtc

hc emit_hook reload
hc detect_monitors
[[ -f ~/.fehbg ]] && source ~/.fehbg

# keybindings
hc keyunbind --all
hc keybind Mod4-l spawn urxvt

# tags
tagnames=(t1 t2 t3 t4 t5 t6 m1 m2 m3 www)
hc rename default ${tagnames[0]} || true
for i in ${!tagnames[@]}; do
    key=$(( $i + 1 ))
    hc add ${tagnames[$i]}
    if (( $key < 10 )); then
        hc keybind $mod-$key       use_index $i
        hc keybind $mod-Shift-$key move_index $i
    fi
done
hc keybind $mod-0       use_index 9
hc keybind $mod-Shift-0 move_index 9

# core
hc keybind $mod-Shift-q quit
hc keybind $mod-Shift-r reload

# focus
hc keybind $mod-h focus left
hc keybind $mod-j focus down
hc keybind $mod-k focus up
hc keybind $mod-l focus right
hc keybind $mod-i jumpto urgent

# moving
hc keybind $mod-Shift-h shift left
hc keybind $mod-Shift-j shift down
hc keybind $mod-Shift-k shift up
hc keybind $mod-Shift-l shift right

# resizing
hc keybind $mod-Control-h resize left +$resizestep
hc keybind $mod-Control-j resize down +$resizestep
hc keybind $mod-Control-k resize up +$resizestep
hc keybind $mod-Control-l resize right +$resizestep

# splitting
hc keybind $mod-Left          split left 0.5
hc keybind $mod-Down          split bottom 0.5
hc keybind $mod-Up            split top 0.5
hc keybind $mod-Right         split right 0.5
hc keybind $mod-Control-space split explode
hc keybind $mod-F9            spawn ~/bin/herb/splitter two
hc keybind $mod-Shift-F9      spawn ~/bin/herb/splitter two "urxvtc -sh 40"

# layouting
hc keybind $mod-x       remove
hc keybind $mod-Shift-x close_and_remove
hc keybind $mod-space   cycle_layout 1
hc keybind $mod-s       floating toggle
hc keybind $mod-f       fullscreen toggle
hc keybind $mod-p       pseudotile toggle
hc keybind $mod-c       cycle

# spawns
hc keybind $mod-Return spawn $term
hc keybind $mod-Shift-Return spawn urxvtc -sh 40
hc keybind $mod-Shift-Delete spawn ~/bin/herb/closeall

# chains
hc keybind $mod-Shift-Left  chain , split left 0.5 , focus left , spawn $term
hc keybind $mod-Shift-Down  chain , split bottom 0.5 , focus down , spawn $term
hc keybind $mod-Shift-Up    chain , split top 0.5 , focus up , spawn $term
hc keybind $mod-Shift-Right chain , split right 0.5 , focus right , spawn $term

# cycling
hc keybind $mod-period use_index +1 --skip-visible
hc keybind $mod-comma  use_index -1 --skip-visible
hc keybind $mod-equal cycle_monitor +1
hc keybind $mod-minus cycle_monitor -1

# mouse
hc mouseunbind --all
hc mousebind $mod-Button1 move
hc mousebind $mod-Button3 resize
hc mousebind $mod-Shift-Button3 zoom


# settings
hc set snap_gap 10
hc set snap_distance 10
hc set focus_stealing_prevention 1
hc set swap_monitors_to_get_tag 0
herbstclient set tree_style '╾│ ├└╼─┐'


# theme
hc attr theme.reset 1
hc set frame_gap 25
hc set frame_bg_transparent 1
hc set frame_border_width 0
hc set window_border_width 1
hc set window_border_active_color 'yellow'
hc set window_border_normal_color '#303030'
hc set window_border_urgent_color 'red'


# rules
hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off


# finish up
hc unlock


# panel(s)
panel=~/bin/herb/panel.sh
for m in `herbstclient list_monitors | cut -d: -f1`; do
    "$panel" $m &
done


# local extras
lcfg=~/.config/herbstluftwm/`hostname`
[[ -f $lcfg ]] && source $lcfg
