# kakrc

# init
set global ui_options ncurses_assistant=cat
set -add global ui_options ncurses_set_title=false
set -add global ui_options ncurses_enable_mouse=false

## regular options
set global indentwidth 4
set global tabstop 4
set global scrolloff 10,1


# color
colorscheme steal


# globals
set global termcmd 'st -c kakoune -e sh -c'


# user
map global user = '<a-i>w:spell-replace<ret>' -docstring 'spell replace word'
map global user c ':comment-line<ret>' -docstring 'comment toggle selected lines'
map global user b ':bn<ret>' -docstring 'next buffer'
map global user B ':bp<ret>' -docstring 'previous buffer'
map global user l ':lint-next-error<ret>' -docstring 'next lint error'
map global user L ':lint-previous-error<ret>' -docstring 'previous lint error'
map global user q ':delete-buffer<ret>' -docstring 'delete buffer'

## external commands
map global user f '|fmt -w 80<ret>' -docstring '|fmt -w 80'
map global user s '|sort -bn<ret>' -docstring '|sort -bn'
map global user p '<a-!>xsel -ob<ret>' -docstring 'append from xsel clipboard'
map global user P '!xsel -ob<ret>' -docstring 'insert from xsel clipboard'
map global user r '|xsel -ob<ret>' -docstring 'replace with xsel clipboard'


# hooks
hook global WinCreate .* %{
    add-highlighter window/ number-lines -hlcursor -separator ' | '
    add-highlighter window/ show-matching
}
hook global NormalKey y|d|c %{ nop %sh{ printf %s "$kak_reg_dquote" | xsel -ib }}
hook global InsertChar \t  %{ exec -draft h@ } # convert tabs to spaces


# lsp
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable


# filetypes

## go
hook global WinSetOption filetype=go %{
    set window indentwidth 0
    set window tabstop 8
    set window lintcmd 'golint-kak'
    set window formatcmd 'goimports'
    set window makecmd 'go build -x'

    lint-enable

    hook buffer BufWritePre .* %{ go-format -use-goimports }
    hook buffer BufWritePost .* lint
}

## shell
hook global WinSetOption filetype=sh %{
    set window lintcmd 'shellcheck -fgcc -Cnever'
    lint-enable
    hook buffer BufWritePost .* lint
}

## python
hook global WinSetOption filetype=python %{
    set window lintcmd 'flake8'
    lint-enable
    hook buffer BufWritePost .* lint
}

## yaml
hook global WinSetOption filetype=yaml %{
    set window indentwidth 2
    set window tabstop 2
    set window lintcmd 'yamllint -f parsable'
    lint-enable
    hook buffer BufWritePost .* lint
}

## dockerfile
hook global WinSetOption filetype=dockerfile %{
    set window lintcmd 'hadolint'
    lint-enable
    hook buffer BufWritePost .* lint
}
